[tools]
golangci-lint = "latest"
"vfox-pulumi:pulumi/pulumi-std" = "2.2.0"
"vfox-pulumi:pulumi/pulumi-converter-terraform" = "1.2.4"
"vfox-pulumi:pulumi/pulumi-gcp" = "9.9.0"
"vfox-pulumi:pulumi/pulumi-aws" = "7.16.0"

[settings]
experimental = true
